title: Government Glossary
description: "A glossary of common government IT and procurement terms, abbreviations and acronyms"
sass:
    style: :compressed

#-- Local configuration
port:    4000
host:    127.0.0.1
